-- Conditional logic
SELECT * 
FROM SNOWFLAKE_LEARNING_DB.ALKETCECAJ_LOAD_SAMPLE_DATA_FROM_S3.ORDERS

SELECT * 
FROM SNOWFLAKE_LEARNING_DB.ALKETCECAJ_LOAD_SAMPLE_DATA_FROM_S3.CUSTOMERS

SELECT * 
FROM SNOWFLAKE_LEARNING_DB.ALKETCECAJ_LOAD_SAMPLE_DATA_FROM_S3.PRODUCTS

SELECT * 
FROM SNOWFLAKE_LEARNING_DB.ALKETCECAJ_LOAD_SAMPLE_DATA_FROM_S3.ORDER_ITEMS